title: Game On Blog
description:
permalink: /:title

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-sitemap

gems:
  - jekyll-paginate-v2

# Pagination Settings
pagination:
  enabled: true
  per_page: 50
  permalink: "/page/:num/"
  title: " Page :num"
  limit: 0
  sort_field: "date"
  sort_reverse: true

feed:
  excerpt_only: true
  tags: true

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - src/
  - package.json
  - package-lock.json
  - webpack.config.js
  - yarn.lock
  - README.md
